[package]
name = "pomo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.30", features = ["serde"] }
clap = { version = "4.2.5", features = ["derive"] }
home = "0.5.5"
humantime = "2.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
